title: Android Native Goodies Documentation
description: Android Native Goodies Documentation
author: Dead Mosquito Games
logo: assets/img/avatar.png
github: https://github.com/ashutosh2k12
about: Android Native Goodies Documentation

baseurl: ""
url: "https://tarasosiris.github.io/android-goodies-docs-PRO"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
